<a href="https://colab.research.google.com/github/Whenning42/linear-algebra-notes/blob/main/linear_algebra_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import jax.numpy as jnp

# William’s Linear Algebra Notes

$\newcommand{\norm}[1]{\left\lVert#1\right\rVert}$

## Latex Background

An latex command is given between two `$` symbols. For example `$m \times n$` renders as $m \times n$.

Here's a table of some common notation:

| Name  | Rendered | Latex |
|-------|--------------|------------|
| Reals | $\mathbb{R}$ | \mathbb{R} |
| Complex | $\mathbb{C}$ | \mathbb{C} |
| Exponentiation | $a^b$, $a^{b+c}$ | a^b, a^{b+c}, note to put more than a yletter in the exponent, we use curly brackets. |
| Element of | $a \in S$ | a \in S |
| Transpose | $A^\top$ | A^\top |
| Dot Product | $x \cdot y$ | x \cdot y |
| Inner Product | $\langle x, y \rangle$ | \langle x, y \rangle |
| Vector Norm | $\norm{x} $ | \newcommand{\norm}[1]{\left\lVert#1\right\rVert} then \norm{x} |
| Orthogonal | $x \perp y$ | x \perp y |

## Matrices

A matrix is an $m \times n$ rectangle consisting of $m$ rows and $n$ columns of scalar values from some field $\mathbb{F}$ (commonly $\mathbb{R}$ or $\mathbb{C}$). We deonte the space of $m \times n$ matrices as $\mathbb{F}^{m \times n}$.

An example $2 \times 3$ matrix $A$ over the reals is:
$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$

### Latex

We can write a bracketed matrix like this in latex:

```
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
```

In [2]:
import numpy as np
import torch
import jax.numpy as jnp

# Note: All libraries use row major notation.
# Sets a to:
# [[1, 2, 3]
#  [4, 5, 6]]
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)

a = jnp.array([[1, 2, 3], [4, 5, 6]])
print(a)

# TODO: Add some simple matrix constructors like eye or diag.

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


## Block Matrices

A block matrix is a matrix that concatenates a rectangular grid of submatrices. Block matrices are denoted as:

$M = \begin{bmatrix} A & B \\ C & D \end{bmatrix}$

With concatenated matrices needing to match the size of their neighbors along their adjacent sides.

In [3]:
# Numpy
a = np.array([[2]])
b = np.array([[4, 6]])
c = np.array([[8]])
d = np.array([[10, 12]])
M = np.block([[a, b], [c, d]])
print(M)

# Torch
#
# Torch doesn't have a block matrix constructor.
# We can however use `torch.cat().
a = torch.tensor(a)
b = torch.tensor(b)
c = torch.tensor(c)
d = torch.tensor(d)
t = torch.cat([a, b], dim=1)
b = torch.cat([c, d], dim=1)
M = torch.cat([t, b], dim = 0)
print(M)

# Jax
a = np.array([[2]])
b = np.array([[4, 6]])
c = np.array([[8]])
d = np.array([[10, 12]])
M = jnp.block([[a, b], [c, d]])
print(M)


[[ 2  4  6]
 [ 8 10 12]]
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
[[ 2  4  6]
 [ 8 10 12]]


## Matrix Transpose

The transpose of a matrix $A$ is denoted as $A^\top$ and is the result of flipping that matrix across its diagonal.

Formally $A^\top$ is defined such that $A^\top_{j,i} = A_{i,j} \ \forall i, j$.

### Latex

We use `^\top` to indicate the transpose, so for example `A^\top` gives us $A^\top$.

In [4]:
# A transpose can be applied in both the Numpy and Torch APIs either
# by reordering axes or swapping two axes. We show both options for
# both APIs. Do note the APIs use different names for these operations.

# Numpy
# `np.transpose` reorders axes.
# `np.swapaxes()` swaps two axes.
a = np.array([[1, 2]])
print(np.transpose(a, axes=(1, 0)))
print(np.swapaxes(a, 0, 1))


# Torch
# `torch.permute` reorders axes.
# `torch.swapaxes()` swaps two axes.
a = torch.Tensor([[1,  2]])
print(torch.permute(a, (1, 0)))
print(torch.transpose(a, 0, 1))

# Jax
a = jnp.array([[1, 2]])
print(jnp.transpose(a, (1, 0)))
print(jnp.swapaxes(a, 0, 1))

[[1]
 [2]]
[[1]
 [2]]
tensor([[1.],
        [2.]])
tensor([[1.],
        [2.]])
[[1]
 [2]]
[[1]
 [2]]


## Matrix Multiplication

The product matrices $A$ and $B$ of size $m \times n$ and $n \times k$ respectively is denoted $AB$ and it's a matrix of size $m \times k$ where:

$AB_{ij} = A_i \cdot B_{:,j}$

In [5]:
# Note: Both numpy and torch use the `*` operator on matrices to be an
# elementwise product, not a matrix multiply.
a = np.array([[1, 5], [2, 6]])
b = np.array([[1, 0], [0, 2]])
print("A\n", a)
print("B\n", b)
print("AB")

# Numpy
# A matrix multiply can be performed with `np.matmul()`, the `@` operator, or an
# einsum.
print(a @ b)
print(np.matmul(a, b))
print(np.einsum('ij,jk->ik', a, b))

# Torch
a = torch.tensor(a)
b = torch.tensor(b)
print(a @ b)
print(torch.matmul(a, b))
print(torch.einsum('ij,jk->ik', a, b))

# Do note that Numpy's einsum is much slower that matmul since it's a python
# implementation whereas Torch and Jax's einsum are close in speed to
# their matmuls.
a = np.ones((500, 500))
b = np.ones((500, 500))
print("Numpy matmul vs einsum:")
%timeit np.matmul(a, b)
%timeit np.einsum('ij,jk->ik', a, b)
a = torch.tensor(a)
b = torch.tensor(b)
print("Torch matmul vs einsum:")
%timeit torch.matmul(a, b)
%timeit torch.einsum('ij,jk->ik', a, b)


A
 [[1 5]
 [2 6]]
B
 [[1 0]
 [0 2]]
AB
[[ 1 10]
 [ 2 12]]
[[ 1 10]
 [ 2 12]]
[[ 1 10]
 [ 2 12]]
tensor([[ 1, 10],
        [ 2, 12]])
tensor([[ 1, 10],
        [ 2, 12]])
tensor([[ 1, 10],
        [ 2, 12]])
Numpy matmul vs einsum:
30.4 ms ± 7.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
101 ms ± 27.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
Torch matmul vs einsum:
18.3 ms ± 6.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
11.6 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Angle Between Vectors

The angle between two vectors $x$ and $y$ is given by the equation

$\cos(\theta) = \frac{\langle x, y \rangle}{\norm{x}\norm{y}}$

and so the angle can be found with this formula

$\theta = \cos^{-1}\left(\frac{\langle x, y \rangle}{\norm{x}\norm{y}}\right)$

Note: When implementing this equation, two edge cases need to be handled:
1. If $\norm{x} = 0$ or $\norm{y} = 0$, then the angle is undefined. In this case returning a ValueError is most appropriate.
2. If due to rounding errors, $\frac{\langle x, y \rangle}{\norm{x}\norm{y}}$ is $\lt -1$ or is $\gt 1$, than $\cos^{-1}$ will fail. In this case, clipping the fraction to between $-1$ and $1$ is an easy fix.


#### Orthogonal Vectors

Orthogonal vectors are vectors $x$ and $y$ such that $\langle x, y \rangle = 0$. We denote two vectors being orthogonal as $x \perp y$ or in Latex, `x \perp y`.

Due to rounding errors, the inner product often won't be exactly $0$ and in which case we can consider two vectors orthogonal numerically if their normed inner product is less than some $\epsilon$.



In [6]:
# The implementation of vector angle (at least in the non-vectorized case)
# is the same for numpy, torch, and jax.

# Numpy
a = np.array([2, 0, 2])
b = np.array([2, 0, -2])

# TODO: How do you do batched bounds checking?
def np_vec_angle(a, b, eps=1e-10):
  norm_a = np.linalg.norm(a)
  norm_b = np.linalg.norm(b)
  if norm_a < eps or norm_b < eps:
    raise ValueError("np_vec_angle doesn't support sub-epsilon length vectors")

  normed_dot = np.dot(a, b) / (norm_a * norm_b)
  return np.arccos(np.clip(normed_dot, -1, 1))
print(np_vec_angle(a, b))

# Torch
def torch_vec_angle(a, b, eps=1e-10):
  # `torch.norm()` requires a float typed tensor. This function accepts any
  # data type that's convertable to floats and does the conversion itself.
  a = a.float()
  b = b.float()
  norm_a = torch.norm(a)
  norm_b = torch.norm(b)
  if norm_a < eps or norm_b < eps:
    raise ValueError("torch_vec_angle doesn't support sub-epsilon length vectors")

  normed_dot = torch.dot(a, b) / (norm_a * norm_b)
  return torch.acos(torch.clip(normed_dot, -1, 1))
a = torch.tensor(a)
b = torch.tensor(b)
print(torch_vec_angle(a, b))

# Jax
a = jnp.array(a)
b = jnp.array(b)
def jnp_vec_angle(a, b, eps=1e-10):
  norm_a = jnp.linalg.norm(a)
  norm_b = jnp.linalg.norm(b)
  if norm_a < eps or norm_b < eps:
    raise ValueError("jnp_vec_angle doesn't support sub-epsilon length vectors")

  normed_dot = jnp.dot(a, b) / (norm_a * norm_b)
  return jnp.arccos(np.clip(normed_dot, -1, 1))
print(jnp_vec_angle(a, b))


1.5707963267948966
tensor(1.5708)
1.5707964


## Orthogonal Matrices

A square matrix $Q \in \mathbb{R}^{n \times n}$ is orthogonal or orthonormal iff $Q^\top Q = QQ^\top = I$.

Due to rounding errors this equality will not generally exactly hold. Instead, numerically we can consider a matrix $Q$ orthogonal if $QQ^\top - I \approx 0$.

The rows and columns of an orthogonal matrix $Q$ for an orthonormal basis of $\mathbb{R}^n$. This follows directly the definition of orthogonal matrices and the matrix product.

Specifically: $Q^\top Q = I \implies \langle Q_i, Q_j \rangle = \langle Q_{:,i}, Q_{:, j}\rangle = \begin{cases} 1 & i = j \\ 0 & i \neq j \end{cases}$ \\
Therefore, the rows and columns of $Q$ are an orthonormal basis of $\mathbb{R}^n$.

In [7]:
# Generate an orthogonal matrix
# Verify QQ^T ~= I
# Perturb Q, verify QQ^T !~= I

# We'll use the QR factorization of an example matrix to construct an
# orthogonal matrix Q.

# Numpy
A = np.array([[1, 2], [3, 4]])
Q, R = np.linalg.qr(A)
Q_T = np.swapaxes(Q, 0, 1)
Qp = Q + np.array([[.05, 0], [0, 0]])
Qp_T = np.swapaxes(Qp, 0, 1)

print("Q is orthogonal:", np.allclose(Q @ Q_T, np.eye(2)))
print("Q's max delta from I:\n", Q @ Q_T - np.eye(2))
print("Qp is orthogonal:", np.allclose(Qp @ Qp_T, np.eye(2)))
print("Qp's max delta from I:\n", Qp @ Qp_T - np.eye(2))
print()

# Torch
Q = torch.tensor(Q).float()
Qp = torch.tensor(Qp).float()
Q_T = torch.transpose(Q, 0, 1)
Qp_T = torch.transpose(Qp, 0, 1)
print("Q is orthogonal:", torch.allclose(Q @ Q_T, torch.eye(2)))
print("Q's max delta from I:\n", Q @ Q_T - torch.eye(2))
print("Qp is orthogonal:", torch.allclose(Qp @ Qp_T, torch.eye(2)))
print("Qp's max delta from I:\n", Qp @ Qp_T - torch.eye(2))
print()


# Jax
A = jnp.array([[1, 2], [3, 4]])
Q, R = jnp.linalg.qr(A)
Q_T = jnp.swapaxes(Q, 0, 1)
Qp = Q + jnp.array([[.05, 0], [0, 0]])
Qp_T = jnp.swapaxes(Qp, 0, 1)
print("Q is orthogonal:", jnp.allclose(Q @ Q_T, jnp.eye(2), atol=1e-6))
print("Q's max delta from I:\n", Q @ Q_T - jnp.eye(2))
print("Qp is orthogonal:", jnp.allclose(Qp @ Qp_T, jnp.eye(2), atol=1e-6))
print("Qp's max delta from I:\n", Qp @ Qp_T - jnp.eye(2))
print()

Q is orthogonal: True
Q's max delta from I:
 [[ 0.0000000e+00 -5.8339229e-18]
 [-5.8339229e-18  0.0000000e+00]]
Qp is orthogonal: False
Qp's max delta from I:
 [[-0.02912278 -0.04743416]
 [-0.04743416  0.        ]]

Q is orthogonal: True
Q's max delta from I:
 tensor([[0., 0.],
        [0., 0.]])
Qp is orthogonal: False
Qp's max delta from I:
 tensor([[-0.0291, -0.0474],
        [-0.0474,  0.0000]])

Q is orthogonal: True
Q's max delta from I:
 [[1.1920929e-07 6.4604976e-08]
 [6.4604976e-08 0.0000000e+00]]
Qp is orthogonal: False
Qp's max delta from I:
 [[-0.02912271 -0.04743412]
 [-0.04743412  0.        ]]



TODO:
- add batching to our examples?
  - I'm not sure which of the functions in this notebook would might be non-obvious in terms of how they generalize to batched matrices.
- vec op
- invertability (above angle between vectors)
- determinant
- eigenvalues
- eigenvectors
- trace
- chapter 2 exercises?