# William’s Linear Algebra Notes

## Latex Background

An latex command is given between two `$` symbols. For example `$m \times n$` renders as $m \times n$.

Here's a table of some common helpful notation:

| Name  | Rendered | Latex |
|-------|--------------|------------|
| Reals | $\mathbb{R}$ | \mathbb{R} |
| Complex | $\mathbb{C}$ | \mathbb{C} |
| Exponentiation | $a^b$, $a^{b+c}$ | a^b, a^{b+c}, note to put more than a letter in the exponent, we use curly brackets. |
| Transpose | $A^\top$ | A^\top |

## Matrices

A matrix is an $m \times n$ rectangle consisting of $m$ rows and $n$ columns of scalar values from some field $\mathbb{F}$ (commonly $\mathbb{R}$ or $\mathbb{C}$). We deonte the space of $m \times n$ matrices as $\mathbb{F}^{m \times n}$.

An example $2 \times 3$ matrix $A$ over the reals is:
$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$

### Latex
```
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
```

In [6]:
import numpy as np
import torch
import jax.numpy as jnp

# Note: All libraries use row major notation.
# Sets a to:
# [[1, 2, 3]
#  [4, 5, 6]]
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)

a = jnp.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


## Block Matrices

A block matrix is a matrix that concatenates a rectangular grid of submatrices. Block matrices are denoted as:

$M = \begin{bmatrix} A & B \\ C & D \end{bmatrix}$

With concatenated matrices needing to match the size of their neighbors along their adjacent sides.

In [16]:
# Numpy
a = np.array([[2]])
b = np.array([[4, 6]])
c = np.array([[8]])
d = np.array([[10, 12]])
M = np.block([[a, b], [c, d]])
print(M)

# Torch
#
# Torch doesn't have a block matrix constructor.
# We can however use `torch.cat().
a = torch.tensor(a)
b = torch.tensor(b)
c = torch.tensor(c)
d = torch.tensor(d)
t = torch.cat([a, b], dim=1)
b = torch.cat([c, d], dim=1)
M = torch.cat([t, b], dim = 0)
print(M)

# Jax
a = np.array([[2]])
b = np.array([[4, 6]])
c = np.array([[8]])
d = np.array([[10, 12]])
M = jnp.block([[a, b], [c, d]])
print(M)


[[ 2  4  6]
 [ 8 10 12]]
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
[[ 2  4  6]
 [ 8 10 12]]


## Matrix Transpose

The transpose of a matrix $A$ is denoted as $A^\top$ and is the result of flipping that matrix across its diagonal.

Formally $A^\top$ is defined such that $A^\top_{j,i} = A_{i,j} \ \forall i, j$.

### Latex

We use `^\top` to indicate the transpose, so for example `A^\top` gives us $A^\top$.

In [34]:
# A transpose can be applied in both the Numpy and Torch APIs either
# by reordering axes or swapping two axes. We show both options for
# both APIs. Do note the APIs use different names for these operations.

# Numpy
# `np.transpose` reorders axes.
# `np.swapaxes()` swaps two axes.
a = np.array([[1, 2]])
print(np.transpose(a, axes=(1, 0)))
print(np.swapaxes(a, 0, 1))


# Torch
# `torch.permute` reorders axes.
# `torch.swapaxes()` swaps two axes.
a = torch.Tensor([[1,  2]])
print(torch.permute(a, (1, 0)))
print(torch.transpose(a, 0, 1))

# Jax
a = jnp.array([[1, 2]])
print(jnp.transpose(a, (1, 0)))
print(jnp.swapaxes(a, 0, 1))

The transpose of [[1 2]] is:
[[1]
 [2]]
[[1]
 [2]]
tensor([[1.],
        [2.]])
tensor([[1.],
        [2.]])
[[1]
 [2]]
[[1]
 [2]]
